deployment:
  tasks:
    - source /home/cayi7350/nodevenv/test.wcgf.com/22/bin/activate

    # 3️⃣ Accès au répertoire du projet
    - cd /home/cayi7350/test.wcgf.com

    # 4️⃣ Nettoyage et mise à jour du code
    - git reset --hard origin/master
    - git pull origin master

    # 5️⃣ Vérification et installation de Next.js et ses dépendances
    - npm install
    -
    # 9️⃣ Build de l'application Next.js
    - npm run build

    - cp public/.htaccess build
