deployment:
  tasks:
    - touch /home/cayi7350/test.wcgf.com/.deploying
    - source /home/cayi7350/nodevenv/test.wcgf.com/22/bin/activate

    # 3️⃣ Accès au répertoire du projet
    - cd /home/cayi7350/test.wcgf.com

    # 4️⃣ Nettoyage et mise à jour du code
    - git reset --hard origin/master
    - git pull origin master

    # 🧹 Nettoyage du cache
    - rm -rf .next
    - rm -rf build

    # 5️⃣ Vérification et installation de Next.js et ses dépendances
    - npm install

    # 9️⃣ Build de l'application Next.js
    - npm run build

    # 📋 Copie des fichiers nécessaires
    - cp public/.htaccess build/

    # 📌 Débloquer le monitor après le déploiement
    - rm -f /home/cayi7350/test.wcgf.com/.deploying

    # 🔄 Redémarrage de l'application
    #- ./restart.sh

    # 🔄 Redémarrage de l'application
    - touch /home/cayi7350/test.wcgf.com/tmp/restart.txt
