---
deployment:
  tasks:
    # Activation de l'environnement virtuel Node.js
    - source /home/cayi7350/nodevenv/wcgf.com/22/bin/activate

    # Accès au répertoire du projet
    - cd /home/cayi7350/wcgf.com

    # Nettoyage et mise à jour du code
    - git reset --hard origin/main
    - git pull

    # Installation et build NextJS (maintenant dans l'environnement virtuel)
    - npm install --prefix /home/cayi7350/nodevenv/wcgf.com/22 --save-dev typescript @types/react @types/node eslint eslint-config-next
    - NODE_ENV=production
    - npm run build

    # Nettoyage du cache NextJS
    - rm -rf .next/cache/*
