---
deployment:
  tasks:
    # Configuration de l'environnement
    - export PATH="$PATH:/opt/alt/alt-nodejs22/root/usr/bin/"
    - export NODE_ENV=production
    
    # Accès au répertoire du projet
    - cd /home/cayi7350/wcgf.com
    
    # Nettoyage et mise à jour du code
    - git reset --hard origin/main
    - git pull
    
    # Installation et build NextJS
    - /opt/alt/alt-nodejs22/root/usr/bin/npm ci
    - /opt/alt/alt-nodejs22/root/usr/bin/npm run build
    
    # Nettoyage du cache NextJS
    - rm -rf .next/cache/*
    
    # Permissions pour le dossier public si nécessaire
    - chmod -R 755 public