runtime: custom
env: flex
service: default

# Spécifier la ressource allouée
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

# Définir les variables d'environnement
env_variables:
  NODE_ENV: "production"

# Assurer que le service écoute sur le bon port
network:
  forwarded_ports:
    - 8080
